label.username= Login Name
label.passWord= Password
label.login= Login

label.name = Name
label.descrption = Description

errors.invalid=${getText(fieldName)} is invalid.
errors.required=${getText(fieldName)} is required.
errors.number=${getText(fieldName)} must be a number.
errors.range=${getText(fieldName)} is not in the range ${min} and ${max}.


images.system.path = C://Users//<user>//Documents//mdr//img//
#images.system.path = //home//<user>//Documents//mdr//img//   # linux path
imagesResize.system.path = C://Users//<user>//Documents//mdr//resizeimg//
#imagesResize.system.path = //home//<user>//Documents//mdr//resizeimg//   # linux path
audio.system.path = C://Users//<user>//Documents//mdr//attachmentFile
#audio.system.path = //home//<user>//Documents//mdr//attachmentFile   # linux path

pdfapp.jarfile.path = C://Users//<user>//Documents//pdfbox-app-2.0.3.jar
#pdfapp.jarfile.path = //home//<user>//Documents//pdfbox-app-2.0.3.jar   # linux path   

image1 = Digital Repository of Medical Manuscripts
image2 = Health
image3 = Meditate
image.extraction.number = 5
image.extraction.timeout = 1200000

config.isArticlesRequired = false
config.createnew.manuscript.subject1.required=true
site.projectName=CEDC