label.username= Login Name
label.passWord= Password
label.login= Login

label.name = Name
label.descrption = Description

errors.invalid=${getText(fieldName)} is invalid.
errors.required=${getText(fieldName)} is required.
errors.number=${getText(fieldName)} must be a number.
errors.range=${getText(fieldName)} is not in the range ${min} and ${max}.


images.system.path = D://Consultancy//YogaSutraApps//root-mdr-media//sciencetechnology//img
imagesResize.system.path = D://Consultancy//YogaSutraApps//root-mdr-media//sciencetechnology//resizeimg//
audio.system.path = D://Consultancy//YogaSutraApps//root-mdr-media//sciencetechnology//attachmentFile

pdfapp.jarfile.path = D://Consultancy//YogaSutraApps//root-mdr-media//pdfbox-app-2.0.3.jar

image1 = Digital Repository of Medical Manuscripts
image2 = Health
image3 = Meditate
image.extraction.number = 5
image.extraction.timeout = 1200000

config.isArticlesRequired = false
config.createnew.manuscript.subject1.required=true
site.projectName=CEDC