hibernate.connection.url =  jdbc:mysql://127.0.0.1:3306/mdr?autoReconnect=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
hibernate.connection.username=root
hibernate.connection.password=password