<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
else if(dataRead.barcodePlaceId=="InterStoreSrc"){
				 divToPrint = '<html>'
				 	+'<style>td{padding:5px;}'
			        +'table.itemTable{}'
			        +'table.itemTable td{border-left: 1px solid #000000;}'
			        +'</style>'
			    	+'<body>'
					+'<div>'
				            +'<table style="width:796px;border:1px solid #000000;" cellspacing="0" cellpadding="0">'
				               +'<tbody>'
				                   +'<tr>'
				                       +'<td colspan="6" style="padding:0px !important;">'
				                            +'<table style="width:100%"  cellspacing="0" cellpadding="0">'
				                                +'<tr style="font-size: 20px;">'
				                                +'<td colspan="2" rowspan=2 style="border-bottom: 1px solid #000000;"><img alt="Sorry fail to load barcode" src="<%=request.getContextPath()%>/images/logo.png"></td>'
			                                    +'<td colspan="2" style="text-align: right;"><img alt="Sorry fail to load barcode" src="<%=request.getContextPath()%>/images/barCode_img/'
				                                    + dataRead.barcodeImageName
													+ '"></td>'
				                                +'</tr>'
				                                +'<tr style="font-size: 20px;">'                        
				                                    +'<td colspan="2" style="text-align: center;border-bottom: 1px solid #000000;">Bar Code Id :'+ dataRead.barcodeId + '</td>'
				                                +'</tr>'
				                            +'</table>'
				                        +'</td>'
				                    +'</tr>'
				                    +'<tr><td><b>Movement Type</td><td style="width:1px;"><b>:</td><td colspan="4">'
				                    +dataRead.movementTypeLabel
				                    +'</td></tr>'
									+'<tr><td><b>Generated By</td><td style="width:1px;"><b>:</td>'
									+'<td>'+dataRead.genratedBy+'</td>'
				                    +'<td><b>Generated Date & Time</td><td style="width:1px;"><b>:</td>'
				                    +'<td>'+dataRead.genratedBarcodeDate+'</td>'
				                    +'</tr>'
				                    +'<tr><td><b>Vehicle Number</td><td style="width:1px;"><b>:</td>'
				                    +'<td>'+dataRead.vehicleNo+'</td>'
				                    +'<td><b>Trolley No</td><td style="width:1px;"><b>:</td>'
				                    +'<td>'+dataRead.trolleyNo+'</td>'
				                    +'</tr>'
				                    +'<tr><td><b>From Location</td><td style="width:1px;"><b>:</td>'
				                    +'<td>'+dataRead.fromLocation+'</td>'
				                    +'<td><b>To Location</td><td style="width:1px;"><b>:</td>'
				                    +'<td>'+dataRead.toLocation+'</td>'
				                    +'</tr>'
				                    +'<tr><td><b>Material Code</td><td style="width:1px;"><b>:</td>'
				                    +'<td>'+dataRead.matCode+'</td>'
				                    +'<td><b>Qty</td><td style="width:1px;"><b>:</td>'
				                    +'<td>'+dataRead.qty+'</td>'
				                    +'</tr>'
				                    +'<tr><td><b>Movement Purpose</td><td style="width:1px;"><b>:</td>'
				                    +'<td>'+dataRead.movePurpose+'</td>'
				                    +'</tr>';
				                                                    
				                                    
				divToPrint = divToPrint +'<tr>'
				                        +'<td colspan="6" style="text-align: center;font-size: 10px;border-top: 1px solid #000000;">&copy; Copyright 2014 GHATGE PATIL INDUSTRIES LTD. All rights reserved.</td>'
				                    +'</tr></tbody></table></div></body></html>';
			
			}


	
	<script type="text/javascript" src="../lib/jquery-1.10.1.min.js"></script>

	<!-- Add mousewheel plugin (this is optional) -->
	<script type="text/javascript" src="../lib/jquery.mousewheel-3.0.6.pack.js"></script>

	<!-- Add fancyBox main JS and CSS files -->
	<script type="text/javascript" src="../source/jquery.fancybox.js?v=2.1.5"></script>
	<link rel="stylesheet" type="text/css" href="../source/jquery.fancybox.css?v=2.1.5" media="screen" />

	<!-- Add Button helper (this is optional) -->
	<link rel="stylesheet" type="text/css" href="../source/helpers/jquery.fancybox-buttons.css?v=1.0.5" />
	<script type="text/javascript" src="../source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>

	<!-- Add Thumbnail helper (this is optional) -->
	<link rel="stylesheet" type="text/css" href="../source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" />
	<script type="text/javascript" src="../source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>

	<!-- Add Media helper (this is optional) -->
	<script type="text/javascript" src="../source/helpers/jquery.fancybox-media.js?v=1.0.6"></script>

	<script type="text/javascript">
		$(document).ready(function() {
			/*
			 *  Simple image gallery. Uses default settings
			 */

			$('.fancybox').fancybox();

			
			
			


		});
	</script>
	<style type="text/css">
		.fancybox-custom .fancybox-skin {
			box-shadow: 0 0 50px #222;
		}

		body {
			max-width: 700px;
			margin: 0 auto;
		}
	</style>
</head>
<body>
	<h1>fancyBox</h1>


	<ul>
		<li><a class="fancybox" href="#inline1" title="Lorem ipsum dolor sit amet">Inline</a></li>
		
	</ul>

	hitjohns
	
</body>
</html>